allow cell customisation for horizontal table
ltht-epr/ltht-react pull request #150
Opened 2022-10-20 10:28 UTC by saqib-airelogic

2022-10-21 13:40 UTC, sambiramairelogic commented on components/styled/table/src/atoms/table.tsx
> +export declare type ReactTableCell = string | FC<ICellProps>
Very minor point but it's the convention in these projects to put interface and type declarations at the bottom of the file

2022-10-21 15:20 UTC, sambiramairelogic commented on components/styled/table/src/index.tsx
> +interface IProps {
Again I know it's a super minor point so sorry to be annoying, but could we just move these interfaces down to the bottom?

2022-10-21 16:09 UTC, saqib-airelogic commented on components/styled/table/src/atoms/table.tsx
> +    mappedCell.id = cellRow.id ?? ''
![image](https://user-images.githubusercontent.com/115567223/197239742-962c9c74-eb68-4450-9e9e-516446d04702.png)

lint doesn't like it I've done it in another way

2022-10-24 13:07 UTC, jsed500 requested changes

2022-10-24 15:01 UTC, jsed500 approved these changes

2022-10-24 15:02 UTC, merged