Fix date logic, with extensive tests
ltht-epr/ltht-react pull request #378
Opened 2024-10-09 11:47 UTC by jsed500

Fixed scenarios where DueDate is not provided (as optional)

Refactored and added full coverage tests to make sure works for all scenarios

2024-10-09 12:57 UTC, Moza805 requested changes
`moment` is a very big framework to include just for parsing ISO date time strings & calculating durations. It's also legacy and unlikely to receive any improvements or updates in the future.

Is it possible to achieve the same goals using `date-fns`  or even plain javascript `Date` objects?

2024-10-16 12:01 UTC, jsed500 commented
Have removed moment references. Uses https://bitbucket.org/LTHT/ehr-client/pull-requests/1618 value now instead of calculating here.

2024-10-16 12:01 UTC, jsed500 commented
Removed date and status from redacted, no idea why they were included initially.

2024-10-16 12:35 UTC, Moza805 approved these changes

2024-10-16 13:44 UTC, merged